[tool.poetry]
name = "sudoku-api"
version = "0.1.0"
description = ""
authors = ["skdv <felipe.osrn@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.3"
strawberry-graphql = {extras = ["debug-server"], version = "^0.142.2"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
